### ISSUE TITLE
Converting Lidar .las / .laz to .tif

### ISSUE THREAD

**Issue by RitaAguiar** [Jabor047/LidarToGeo#1]
I would like to suggest a new feature to be able to convert a lidar .las / .laz to a .tif file.
The documentation is scarce so I don't know if this has already been implemented or not.

**Comment by Jabor047** [comment]
In the RasterGetter Class, there is a function called get_raster_terrain this creates both a tif file and a las file so conversion between the two is not necessary, I've updated the docs to reflect this. You can find the documentation [here](https://jabor047.github.io/LidarToGeo/docs/build/html/generated/src.lidarToGeo.get_data.RasterGetter.get_raster_terrain.html)
